server:
  port: 8484
spring:
  application:
    name: book-servers-provider


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  redis:
    port: 6379
    host: localhost


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yzk46.book.entities

