server:
  port: 80
spring:
  application:
    name: book-servers-consumer

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

service-url:
  createUrl: http://book-servers-provider/book/create
  getBookUrl: http://book-servers-provider/book/get/
  loginUrl: http://book-servers-provider/auth/login
  registerUrl: http://book-servers-provider/auth/register
  getByTagUrl: http://book-servers-provider/book
  getTagUrl: http://book-servers-provider/tag/get
  searchUrl: http://book-servers-provider/search
  searchRecommendUrl: http://book-servers-provider/search/recommend
  addCommentUrl: http://book-servers-provider/comment/add
  getCommentUrl: http://book-servers-provider/comment/get/
  addLikeUrl: http://book-servers-provider/comment/like
