server:
  port: 80
spring:
  application:
    name: book-servers-consumer

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

service-url:
  createUrl: http://book-servers-provider/book/create
  getBookUrl: http://book-servers-provider/book/get/
  loginUrl: http://book-servers-provider/auth/login
  registerUrl: http://book-servers-provider/auth/register
  getByTagUrl: http://book-servers-provider/book
  getTagUrl: http://book-servers-provider/tag/get
  searchUrl: http://book-servers-provider/search
  searchRecommendUrl: http://book-servers-provider/search/recommend
  addCommentUrl: http://book-servers-provider/comment/add
  getCommentUrl: http://book-servers-provider/comment/get/
  addLikeUrl: http://book-servers-provider/comment/like
  recordUrl: http://book-servers-provider/record/add
  setRelateUrl: http://book-servers-provider/relate/set
  getRelateUrl: http://book-servers-provider/relate/get
  getRecommendUrl: http://book-servers-provider/relate/guess
  getRelateNumUrl:  http://book-servers-provider/relate/getByBook
  addHisUrl: http://book-servers-provider/his/add
  getHisUrl: http://book-servers-provider/his/get
  getRankUrl: http://book-servers-provider/book/getRank
  getInterestUrl: http://book-servers-provider/user/interest
  addInterestUrl: http://book-servers-provider/user/interest/add
